# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 536a13cdbb37560342c9c83409b3d47bdc5c9465d3481793fd303e420b032b09f009c6cb9f20c88951ef300b61f571cae3e7c22a76c4ad8fbf47083a0b8f66a1

test:
  secret_key_base: 3a6d140eca2a3e354e84b3586fcdf176d7af426a872fef7813381cde887c5475fabc925f1d8b1bb7ee594443006358a5678bed1f4361c28c3ef03cbb9e954851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
